version: 0.2

phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
      - npm audit fix
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod              
      - zip -r site.zip dist/my-personal-menu
  post_build:
    commands:
      - aws s3 sync ./dist/my-personal-menu s3://mpm.seankendall.com --acl 'public-read' --delete
artifacts:
  files:
    - site.zip