// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:afdebbb7-4a93-4a10-95fa-e3e6da8f1588",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Nu4jTYXbf",
    "aws_user_pools_web_client_id": "451jakdnolad9o5qa1iqdfiv15"
};


export default awsmobile;
